
name: Go-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_upload_assets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.2

      - name: Update go.mod to use Go 1.17
        run: |
          sed -i 's/go 1.20/go 1.17/' go.mod

      - name: Download dependencies
        run: go mod tidy

      - name: Build Linux arm64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o tgState main.go

      - name: Zip Linux amd64
        run: |
          sudo apt-get install -y zip
          zip tgState_arm64.zip tgState

      - name: Delete tgState arm64
        run: |
          rm tgState

      - name: Build Linux amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o tgState main.go

      - name: Zip Linux amd64
        run: |
          sudo apt-get install -y zip
          zip tgState.zip tgState
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jp0id/tgdisk:latest
